# Generated by Django 3.2.3 on 2021-05-27 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0002_alter_useranswer_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='useranswer',
            name='quiz_session_id',
            field=models.UUIDField(default=1),
            preserve_default=False,
        ),
    ]
